{{- if .Values.advanced.createServiceAccount }}
{{- $bc := .Values.buildconfig -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "shipwright-build.serviceAccountName" . }}
  namespace: {{ $bc.namespace }}
  labels:
    {{- include "shipwright-build.labels" . | nindent 4 }}
  {{- if .Values.conversion.addAnnotations }}
  annotations:
    {{ .Values.conversion.annotationPrefix }}/purpose: "builder-service-account"
  {{- end }}
{{- if or $bc.source.sourceSecret $bc.output.pushSecret }}
secrets:
{{- if $bc.source.sourceSecret }}
- name: {{ $bc.source.sourceSecret }}
{{- end }}
{{- if $bc.output.pushSecret }}
- name: {{ $bc.output.pushSecret }}
{{- end }}
{{- end }}
{{- end }}
