#!/usr/bin/env python3
"""Render a linked Markdown backlog report from a collected JSON snapshot."""

from __future__ import annotations

import argparse
import json
import os
import sys
import tempfile
from collections import Counter
from datetime import datetime
from pathlib import Path
from typing import Any, Iterable
from urllib.parse import quote_plus


ACTIVE_STATUSES = {"Todo", "In progress", "In review"}
TERMINAL_STATUSES = {"Done", "Closed"}
FAILURE_CONCLUSIONS = {
    "ACTION_REQUIRED",
    "CANCELLED",
    "ERROR",
    "FAILURE",
    "STALE",
    "TIMED_OUT",
}
SUCCESS_CONCLUSIONS = {"NEUTRAL", "SKIPPED", "SUCCESS"}


def markdown_escape(value: Any) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def markdown_link(label: Any, url: str) -> str:
    return f"[{markdown_escape(label)}]({url})"


def repository_url(repository: str, suffix: str = "") -> str:
    return f"https://github.com/{repository}{suffix}"


def issue_query_url(repository: str, *terms: str) -> str:
    query = " ".join(("is:issue", "is:open", *terms))
    return repository_url(repository, f"/issues?q={quote_plus(query)}")


def pull_query_url(repository: str, *terms: str) -> str:
    query = " ".join(("is:pr", "is:open", *terms))
    return repository_url(repository, f"/pulls?q={quote_plus(query)}")


def project_item_url(item: dict[str, Any]) -> str | None:
    return item.get("content", {}).get("url")


def project_index(items: Iterable[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    return {
        url: item
        for item in items
        if (url := project_item_url(item)) is not None
    }


def labels_for(item: dict[str, Any]) -> list[str]:
    return [label["name"] for label in item.get("labels", [])]


def check_state(pull_request: dict[str, Any]) -> str:
    checks = pull_request.get("statusCheckRollup") or []
    if not checks:
        return "none"
    conclusions = [
        check.get("conclusion") or check.get("state") for check in checks
    ]
    if any(value in FAILURE_CONCLUSIONS for value in conclusions):
        return "failing"
    if all(value in SUCCESS_CONCLUSIONS for value in conclusions):
        return "passing"
    return "pending"


def age_days(timestamp: str, generated_at: datetime) -> int:
    created = datetime.fromisoformat(timestamp.replace("Z", "+00:00"))
    return max(0, (generated_at - created).days)


def count_if(items: Iterable[dict[str, Any]], predicate: Any) -> int:
    return sum(1 for item in items if predicate(item))


def table(headers: list[str], rows: list[list[Any]]) -> list[str]:
    output = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    output.extend(
        "| " + " | ".join(markdown_escape(cell) for cell in row) + " |"
        for row in rows
    )
    return output


def linked_cell(value: Any, url: str) -> str:
    return markdown_link(value, url)


def render(snapshot: dict[str, Any]) -> str:
    generated_at = datetime.fromisoformat(snapshot["generatedAt"])
    repositories = snapshot["configuration"]["repositories"]
    project_config = snapshot["configuration"]["project"]
    project_url = project_config["url"]
    project = snapshot["project"]
    project_items = project["items"]
    by_url = project_index(project_items)

    lines = [
        "# Crane backlog status",
        "",
        f"Generated at: `{snapshot['generatedAt']}`",
        "",
        "This file is generated by `update_backlog.py`. Do not edit it manually.",
        "",
        "## Summary",
        "",
    ]

    summary_rows: list[list[Any]] = []
    total_issues = 0
    total_prs = 0
    total_project = 0
    for repository in repositories:
        data = snapshot["repositories"][repository]
        issues = data["issues"]
        pull_requests = data["pullRequests"]
        work = [*issues, *pull_requests]
        included = count_if(work, lambda item: item["url"] in by_url)
        total_issues += len(issues)
        total_prs += len(pull_requests)
        total_project += included
        unlabeled = count_if(issues, lambda item: not item.get("labels"))
        unassigned = count_if(issues, lambda item: not item.get("assignees"))
        no_milestone = count_if(issues, lambda item: item.get("milestone") is None)
        summary_rows.append(
            [
                markdown_link(repository, repository_url(repository)),
                linked_cell(len(issues), issue_query_url(repository)),
                linked_cell(len(pull_requests), pull_query_url(repository)),
                linked_cell(unlabeled, issue_query_url(repository, "no:label")),
                linked_cell(unassigned, issue_query_url(repository, "no:assignee")),
                linked_cell(
                    no_milestone,
                    issue_query_url(repository, "no:milestone"),
                ),
                linked_cell(f"{included}/{len(work)}", project_url),
            ]
        )
    summary_rows.append(
        [
            "Total",
            total_issues,
            total_prs,
            "",
            "",
            "",
            f"{total_project}/{total_issues + total_prs}",
        ]
    )
    lines.extend(
        table(
            [
                "Repository",
                "Open issues",
                "Open PRs",
                "Unlabeled issues",
                "Unassigned issues",
                "No milestone",
                "In project",
            ],
            summary_rows,
        )
    )

    lines.extend(["", "## Issue age", ""])
    age_rows: list[list[Any]] = []
    for repository in repositories:
        issues = snapshot["repositories"][repository]["issues"]
        buckets = Counter()
        for issue in issues:
            age = age_days(issue["createdAt"], generated_at)
            if age < 30:
                buckets["<30"] += 1
            elif age < 90:
                buckets["30-89"] += 1
            elif age < 180:
                buckets["90-179"] += 1
            elif age < 365:
                buckets["180-364"] += 1
            else:
                buckets[">=365"] += 1
        age_rows.append(
            [
                markdown_link(repository, issue_query_url(repository)),
                buckets["<30"],
                buckets["30-89"],
                buckets["90-179"],
                buckets["180-364"],
                buckets[">=365"],
            ]
        )
    lines.extend(
        table(
            ["Repository", "<30d", "30-89d", "90-179d", "180-364d", ">=365d"],
            age_rows,
        )
    )

    lines.extend(["", "## Pull request health", ""])
    pr_rows: list[list[Any]] = []
    for repository in repositories:
        pull_requests = snapshot["repositories"][repository]["pullRequests"]
        states = Counter(check_state(pull_request) for pull_request in pull_requests)
        review = Counter(
            pull_request.get("reviewDecision") or "unset"
            for pull_request in pull_requests
        )
        pr_rows.append(
            [
                markdown_link(repository, pull_query_url(repository)),
                len(pull_requests),
                count_if(pull_requests, lambda item: item.get("isDraft", False)),
                states["failing"],
                states["pending"],
                states["passing"],
                states["none"],
                review["REVIEW_REQUIRED"],
                review["CHANGES_REQUESTED"],
                review["APPROVED"],
            ]
        )
    lines.extend(
        table(
            [
                "Repository",
                "Open",
                "Draft",
                "Failing",
                "Pending",
                "Passing",
                "No checks",
                "Review required",
                "Changes requested",
                "Approved",
            ],
            pr_rows,
        )
    )

    crane_data = snapshot["repositories"].get("migtools/crane")
    if crane_data is not None:
        lines.extend(["", "### migtools/crane check results", ""])
        check_totals: dict[str, Counter[str]] = {}
        for pull_request in crane_data["pullRequests"]:
            for check in pull_request.get("statusCheckRollup") or []:
                name = check.get("name") or "Unnamed check"
                conclusion = check.get("conclusion") or check.get("status") or "PENDING"
                if conclusion == "SKIPPED":
                    state = "skipped"
                elif conclusion in FAILURE_CONCLUSIONS:
                    state = "failing"
                elif conclusion in SUCCESS_CONCLUSIONS:
                    state = "passing"
                else:
                    state = "pending"
                check_totals.setdefault(name, Counter())[state] += 1
        check_rows = [
            [
                check_name,
                sum(counts.values()),
                counts["passing"],
                counts["failing"],
                counts["pending"],
                counts["skipped"],
            ]
            for check_name, counts in sorted(
                check_totals.items(), key=lambda item: (-sum(item[1].values()), item[0])
            )
        ]
        lines.extend(
            table(
                ["Check", "Observed", "Passing", "Failing", "Pending", "Skipped"],
                check_rows,
            )
        )
        lines.append(
            "Counts are check-run observations across open PRs. A PR rerun can produce more than one observation."
        )

    lines.extend(["", "## Labels", ""])
    label_rows: list[list[Any]] = []
    for repository in repositories:
        data = snapshot["repositories"][repository]
        used = Counter(
            label
            for issue in data["issues"]
            for label in labels_for(issue)
        )
        top = ", ".join(f"`{name}` ({count})" for name, count in used.most_common(5))
        label_rows.append(
            [
                markdown_link(repository, repository_url(repository, "/labels")),
                len(data["labels"]),
                count_if(data["issues"], lambda item: not item.get("labels")),
                top or "None used",
            ]
        )
    lines.extend(
        table(
            ["Repository", "Available", "Unlabeled open issues", "Most used"],
            label_rows,
        )
    )

    lines.extend(["", "## Open milestones", ""])
    milestone_rows: list[list[Any]] = []
    milestone_summary_rows: list[list[Any]] = []
    for repository in repositories:
        data = snapshot["repositories"][repository]
        milestones = data["milestones"]
        releases = data.get("releases", [])
        latest_release = next(
            (release for release in releases if release.get("isLatest")), None
        )
        no_due_date = count_if(milestones, lambda item: not item.get("due_on"))
        empty = count_if(milestones, lambda item: item.get("open_issues", 0) == 0)
        issues_without_milestone = count_if(
            data["issues"], lambda item: item.get("milestone") is None
        )
        latest_release_cell = "None"
        if latest_release:
            latest_release_cell = markdown_link(
                latest_release.get("tagName") or latest_release.get("name"),
                latest_release["url"],
            )
        milestone_summary_rows.append(
            [
                markdown_link(repository, repository_url(repository, "/milestones")),
                len(milestones),
                no_due_date,
                empty,
                linked_cell(
                    issues_without_milestone,
                    issue_query_url(repository, "no:milestone"),
                ),
                latest_release_cell,
            ]
        )
        if not milestones:
            milestone_rows.append(
                [
                    markdown_link(repository, repository_url(repository, "/milestones")),
                    "None",
                    0,
                    "",
                ]
            )
            continue
        for milestone in milestones:
            due = (milestone.get("due_on") or "")[:10]
            milestone_rows.append(
                [
                    markdown_link(repository, repository_url(repository, "/milestones")),
                    markdown_link(
                        milestone["title"],
                        repository_url(repository, f"/milestone/{milestone['number']}"),
                    ),
                    milestone.get("open_issues", 0),
                    due or "None",
                ]
            )
    lines.extend(
        table(
            ["Repository", "Milestone", "Open items", "Due date"],
            milestone_rows,
        )
    )
    lines.extend(["", "### Milestone hygiene", ""])
    lines.extend(
        table(
            [
                "Repository",
                "Open milestones",
                "Without due date",
                "Empty",
                "Open issues without milestone",
                "Latest release",
            ],
            milestone_summary_rows,
        )
    )

    configured_urls = {repository_url(repository) for repository in repositories}
    selected_project_items = [
        item for item in project_items if item.get("repository") in configured_urls
    ]
    lines.extend(["", "## GitHub Project", ""])
    lines.append(
        f"Project: {markdown_link(project['metadata']['title'], project_url)}. "
        f"Total items: {project['metadata']['items']['totalCount']}. "
        f"Configured-repository items: {len(selected_project_items)}."
    )
    lines.extend(["", "### Open backlog coverage", ""])
    coverage_rows: list[list[Any]] = []
    missing_items: list[tuple[str, str, dict[str, Any]]] = []
    open_terminal: list[tuple[str, str, dict[str, Any], dict[str, Any]]] = []
    active_items: list[dict[str, Any]] = []
    for repository in repositories:
        data = snapshot["repositories"][repository]
        issue_included = 0
        pr_included = 0
        for kind, items in (
            ("Issue", data["issues"]),
            ("Pull request", data["pullRequests"]),
        ):
            for item in items:
                project_item = by_url.get(item["url"])
                if project_item is None:
                    missing_items.append((repository, kind, item))
                    continue
                if kind == "Issue":
                    issue_included += 1
                else:
                    pr_included += 1
                status = project_item.get("status")
                if status in TERMINAL_STATUSES:
                    open_terminal.append((repository, kind, item, project_item))
                elif status in ACTIVE_STATUSES:
                    active_items.append(project_item)
        coverage_rows.append(
            [
                markdown_link(repository, project_url),
                f"{issue_included}/{len(data['issues'])}",
                f"{pr_included}/{len(data['pullRequests'])}",
                len(data["issues"]) + len(data["pullRequests"]) - issue_included - pr_included,
            ]
        )
    lines.extend(
        table(
            ["Repository", "Issues", "Pull requests", "Missing items"],
            coverage_rows,
        )
    )

    lines.extend(["", "### Active field coverage", ""])
    field_rows = []
    for name, key in (
        ("Status", "status"),
        ("Priority", "priority"),
        ("Size", "size"),
        ("Sprint", "sprint"),
        ("Estimate", "estimate"),
        ("Start date", "start date"),
        ("Target date", "target date"),
    ):
        set_count = count_if(active_items, lambda item, field=key: item.get(field) is not None)
        coverage = (set_count / len(active_items) * 100) if active_items else 0
        field_rows.append([name, set_count, len(active_items), f"{coverage:.1f}%"])
    lines.extend(table(["Field", "Set", "Active items", "Coverage"], field_rows))

    lines.extend(["", "### Open items in terminal project states", ""])
    if open_terminal:
        terminal_rows = [
            [
                repository,
                kind,
                markdown_link(f"#{item['number']} {item['title']}", item["url"]),
                project_item.get("status", "unset"),
            ]
            for repository, kind, item, project_item in open_terminal
        ]
        lines.extend(table(["Repository", "Type", "Item", "Status"], terminal_rows))
    else:
        lines.append("None.")

    lines.extend(["", "### Missing project items", ""])
    if missing_items:
        missing_rows = [
            [
                repository,
                kind,
                markdown_link(f"#{item['number']} {item['title']}", item["url"]),
            ]
            for repository, kind, item in missing_items
        ]
        lines.extend(table(["Repository", "Type", "Item"], missing_rows))
    else:
        lines.append("None.")

    lines.extend(["", "### Enabled project workflows", ""])
    workflow_rows = [
        [workflow["number"], workflow["name"], workflow["updatedAt"]]
        for workflow in project["workflows"]
        if workflow.get("enabled")
    ]
    lines.extend(table(["Number", "Workflow", "Updated"], workflow_rows))
    lines.append("")
    return "\n".join(lines)


def write_text_atomic(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        "w", encoding="utf-8", dir=path.parent, delete=False
    ) as temporary:
        temporary.write(content)
        temporary_path = Path(temporary.name)
    os.replace(temporary_path, path)


def parse_args() -> argparse.Namespace:
    directory = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        default=directory / "backlog-data.json",
        help="collected JSON snapshot",
    )
    parser.add_argument(
        "--output",
        type=Path,
        help="write Markdown to this path instead of stdout",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        snapshot = json.loads(args.input.read_text(encoding="utf-8"))
        content = render(snapshot)
        if args.output:
            write_text_atomic(args.output, content)
        else:
            sys.stdout.write(content)
    except (OSError, KeyError, TypeError, ValueError, json.JSONDecodeError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
