apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"build.openshift.io/v1","kind":"BuildConfig","metadata":{"annotations":{},"labels":{"app":"sample-nodejs-webhook"},"name":"sample-nodejs-webhook","namespace":"demo-buildconfig"},"spec":{"output":{"to":{"kind":"ImageStreamTag","name":"sample-nodejs-webhook:latest"}},"source":{"contextDir":"source-build","git":{"ref":"main","uri":"https://github.com/shipwright-io/sample-nodejs"},"type":"Git"},"strategy":{"sourceStrategy":{"env":[{"name":"NPM_MIRROR","value":"https://registry.npmjs.org"}],"from":{"kind":"ImageStreamTag","name":"nodejs:18-ubi8","namespace":"openshift"}},"type":"Source"},"triggers":[{"imageChange":{"paused":true},"type":"ImageChange"},{"github":{"secretReference":{"name":"github-webhook-secret"}},"type":"GitHub"}]}}
  creationTimestamp: "2026-09-07T07:21:34Z"
  generation: 2
  labels:
    app: sample-nodejs-webhook
  managedFields:
  - apiVersion: build.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:output:
          f:to: {}
        f:runPolicy: {}
        f:source:
          f:contextDir: {}
          f:git:
            .: {}
            f:ref: {}
            f:uri: {}
          f:type: {}
        f:strategy:
          f:sourceStrategy:
            .: {}
            f:env: {}
            f:from: {}
          f:type: {}
        f:triggers: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2026-09-07T07:30:23Z"
  name: sample-nodejs-webhook
  namespace: demo-buildconfig
  resourceVersion: "137458"
  uid: 3c164b46-51dd-4945-8a7b-2d530260bcdc
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: sample-nodejs-webhook:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: source-build
    git:
      ref: main
      uri: https://github.com/shipwright-io/sample-nodejs
    type: Git
  strategy:
    sourceStrategy:
      env:
      - name: NPM_MIRROR
        value: https://registry.npmjs.org
      from:
        kind: ImageStreamTag
        name: nodejs:18-ubi8
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - imageChange:
      paused: true
    type: ImageChange
  - github:
      secretReference:
        name: github-webhook-secret
    type: GitHub
status:
  lastVersion: 0
