apiVersion: shipwright.io/v1beta1
kind: Build
metadata:
  name: s2i-build-template
  namespace: default
  labels:
    app.kubernetes.io/managed-by: kustomize
    migration.konveyor.io/source-kind: BuildConfig
spec:
  source:
    type: Git
    git:
      url: https://example.invalid/repo.git
  strategy:
    kind: ClusterBuildStrategy
    name: source-to-image
  output:
    image: image-registry.example.invalid/ns/app:latest
    pushSecret: push-secret
  paramValues:
    - name: builder-image
      value: registry.redhat.io/ubi8/openjdk-11:latest