apiVersion: v1
data:
  MYSQL_ROOT_PASSWORD: TTNtb2dHcG1RbFF4QWc3ek9tOVBPUT09
  MYSQL_WORDPRESS_PASSWORD: RjA0NXl2MmJNNllKaFJockFEalZzUT09
  WORDPRESS_ADMIN_PASSWORD: MzBxcEZsSUlxTTRUK1NMbQ==
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"MYSQL_ROOT_PASSWORD":"TTNtb2dHcG1RbFF4QWc3ek9tOVBPUT09","MYSQL_WORDPRESS_PASSWORD":"RjA0NXl2MmJNNllKaFJockFEalZzUT09","WORDPRESS_ADMIN_PASSWORD":"MzBxcEZsSUlxTTRUK1NMbQ=="},"kind":"Secret","metadata":{"annotations":{},"name":"wordpress-secrets-hh2m44dbd9","namespace":"default"},"type":"Opaque"}
  creationTimestamp: "2026-06-05T08:32:55Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:MYSQL_ROOT_PASSWORD: {}
        f:MYSQL_WORDPRESS_PASSWORD: {}
        f:WORDPRESS_ADMIN_PASSWORD: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:type: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2026-06-05T08:32:55Z"
  name: wordpress-secrets-hh2m44dbd9
  namespace: default
  resourceVersion: "5109"
  uid: 082180e9-53ca-4e0c-aab7-1d6d29b55f6b
type: Opaque
